name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
  - repository: self
    type: github
    endpoint: DfE-Digital
    name: DFE-Digital/login.dfe.help
    ref: master
trigger:
  branches:
    include:
    - NSA-3397
    exclude:
    - master
    - release/*
    - develop
    - hotfix/*

stages:

  - stage: preDeploy
    displayName: preDeploy
    jobs:
    - template: login-dfe-help-predeploy.yml
      parameters:
        serviceConnection: $(ServiceConnection)
        subscriptionId: $(SubscriptionId)   


  - stage: CreateRG
    dependsOn: preDeploy
    displayName: 'Create and Tag Resource Group'
    jobs:
    - template: login-dfe-help-rg.yml
      parameters: 
        serviceConnection: $(devServiceConnection)
        subscriptionId: $(devSubscriptionId)
        devresourceGroupName: $(devresourceGroupName)
        EnvironmentTag: $(EnvironmentTag)
        ParentBusinessTag: $(subscriptionId)
        ServiceOffering: $(ServiceOffering)
#
#  - stage: Copyfiles
#    dependsOn: preDeploy
#    displayName: Copyfiles
#    jobs:
#    - template: login-dfe-help-copy-files.yml
#      parameters:
#        ArtifactStagingDirectory: $(ArtifactStagingDirectory)
#        DefaultWorkingDirectory: $(DefaultWorkingDirectory)
#    
#  - stage: PublishFiles
#    dependsOn: Copyfiles
#    displayName: PublishFiles
#    jobs:
#    - template: login-dfe-help-copy-files.yml
#      parameters:
#        ArtifactStagingDirectory: $(ArtifactStagingDirectory)
#        DefaultWorkingDirectory: $(DefaultWorkingDirectory)