parameters:
- name: devresourceGroupName
  type: string
- name: EnvironmentTag
  type: string
- name: ParentBusinessTag
  type: string
- name: ServiceOffering
  type: string
- name: serviceConnection
  type: string
- name: subscriptionId
  type: string

jobs:
- job: Phase_1
  displayName: Phase 1
  cancelTimeoutInMinutes: 1
  pool:
    vmImage: windows-2019
  steps:
  - task: AzurePowerShell@3
    displayName: 'Create and Tag Resource Group'
    inputs:
      azureSubscription: '${{parameters.serviceConnection}}'
      ConnectedServiceNameARM: "${{parameters.ServiceConnection}}"
      subscriptionId: '${{parameters.subscriptionId}}'
      ScriptPath: '$(System.DefaultWorkingDirectory)/login.dfe.infrastructure/drop/powershell/Set-ResourceGroupTags.ps1'
      ScriptArguments: '-ResourceGroupName "$(devresourceGroupName)" -Environment "$(EnvironmentTag)" -ParentBusiness "$(ParentBusinessTag)" -ServiceOffering "$(ServiceOffering)"'
      azurePowerShellVersion: LatestVersion